{% set name = "iohub" %}
{% set version = "0.1.0.dev5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/iohub-{{ version }}.tar.gz
  sha256: e81b7057693173b9e72ccb04d1d3483199d055da6ade9179fef5957e9abcdbf5

build:
  entry_points:
    - iohub=iohub.cli.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
    - wheel
  run:
    - natsort >=7.1.1
    - ndtiff >=2.2.1
    - pandas >=1.5.2
    - pillow >=9.4.0
    - pydantic >=1.10.2,<2
    - python >={{ python_min }}
    - python-blosc2
    - tifffile >=2023.2.3,<2023.3.15
    - tqdm
    - zarr >=2.13,<2.16

test:
  imports:
    - iohub
  commands:
    - pip list
    - pip check
    - iohub --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/iohub
  summary: N-dimensional bioimaging data I/O with OME metadata in Python
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/czbiohub-sf/iohub

extra:
  recipe-maintainers:
    - goanpeca
